### PR TITLE
✏ Fix typo in `docs/tutorial/arguments/optional.md`

### PR DESCRIPTION
**Pull request by tadasgedgaudas**
:sunglasses:

### CODE REVIEW

**Comment by gyKa** [comment]
good catch! 💪

**Comment by JacobKochems** [comment]
### PR Review Report
according to this [guide lines](https://typer.tiangolo.com/help-typer/#review-pull-requests)

---
**TL;DR:** No code changed. The formatting/spelling checks out.

---
#### Understand the problem
The typo can **not** be solved in a different way.

#### Check the code
##### Reproduce the claimed solution
 * No code to be run.
 * No need for a local clone.

#### Tests
Nothing to test.

#### Documentation
I looked at the linked docs preview and the formatting/spelling checks out.

**Review by svlandeg — APPROVED** [review]
Thanks, good catch!

**Comment by tiangolo** [comment]
Great, thanks! :rocket:

**Pull request merged**
