### PR TITLE
⬆ Upgrade Rich, support 13.x

### PR DESCRIPTION
**Pull request by musicinmybrain**
Based on the changelog, the only relevant breaking change is that support for Python 3.6 is removed:

https://github.com/Textualize/rich/blob/v13.0.0/CHANGELOG.md#1300---2022-12-30

This is OK even though we support Python 3.6 in typer, because we do still allow older versions of rich that are compatible with Python 3.6.

### CODE REVIEW

**Comment by mzebrak** [comment]
I am very much looking forward to this change as currently there is no easy way to use the latest versions of `textualize` along with the `typer` since:

```
Because no versions of textual match >0.10.1,<0.11.0
 and textual (0.10.1) depends on rich (>12.6.0), textual (>=0.10.1,<0.11.0) requires rich (>12.6.0).
Because typer (0.7.0) depends on rich (>=10.11.0,<13.0.0)
 and no versions of rich match >12.6.0,<13.0.0, typer (0.7.0) requires rich (>=10.11.0,<=12.6.0).
Thus, textual (>=0.10.1,<0.11.0) is incompatible with typer (0.7.0).
So, because my_app depends on both typer (0.7.0) and textual (^0.10.1), version solving failed.
```

**Comment by kkirsche** [comment]
Can any actions help offload the review responsibilities from tialango or other maintainers? I understand he's busy across multiple projects and his day job, but happy to help if there is a way to get this merged

**Review by atmartinez — APPROVED** [review]
This looks good to me. Tests pass for each Python version with 3.6 installing Rich 12.6, and 3.7+ installing 13+. 

I'm not a maintainer, but I hope this review helps with getting this merged by one.

**Review by RomainBrault — APPROVED** [review]

**Comment by deepyaman** [comment]
100% support this (and generally not capping dependencies, even more so for a less-actively maintained project; see a lot of great arguments in https://iscinumpy.dev/post/bound-version-constraints/).

That being said, `rich` is an extra, so an easy workaround is to just depend on the additional dependencies:

```diff
- typer[all]
+ typer
+ colorama >=0.4.3,<0.5.0
+ shellingham >=1.3.0,<2.0.0
+ rich >=10.11.0,<14.0.0
```

Not perfect, but it gets the job done for a consuming library blocked by this.

**Comment by SRv6d** [comment]
@musicinmybrain Can you merge this ?

**Comment by musicinmybrain** [comment]
> @musicinmybrain Can you merge this ?

I’m afraid not. I’m not a maintainer of this project, and I have no permissions on the repository.

**Comment by SRv6d** [comment]
My bad, I falsely assumed your PR was reviewed by maintainers.

**Comment by tiangolo** [comment]
Thanks @musicinmybrain! :rocket: 

And thanks @atmartinez for you review with a comment explaining what you did to test it, that helps a lot! :bow: 

This will be available in Typer `0.8.0` released in the next few hours.

**Pull request merged**
