### PR TITLE
✏ Fix double "and" typo in first-steps tutorial

### PR DESCRIPTION
**Pull request by softwarebloat**

### CODE REVIEW

**Review by svlandeg — APPROVED** [review]
Thanks!

**Comment by softwarebloat** [comment]
of course it's not an urgent PR but i was wondering why some status hasn't run :thinking:

**Comment by svlandeg** [comment]
Good question which I'll have to defer to @tiangolo ...

**Comment by tiangolo** [comment]
Thanks for the contribution @softwarebloat! :mag: 

The missing checks were probably because I added some new required CI checks that probably didn't exist when you created this PR, but after updating the branch now they are found and run. :rocket: 

Thanks @svlandeg as always! :cake: :bow:

**Pull request merged**
